name: bidi
description: Implementation of the Bidi algorithm, as described in http://www.unicode.org/reports/tr9/tr9-17.html.
version: 2.0.6
repository: https://github.com/xclud/dart_bidi
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
  file: ^6.1.4