name: bidi
description: Implementation of the Unicode Bidirectional Algorithm (UBA) as described in https://unicode.org/reports/tr9/.
version: 2.0.9
repository: https://github.com/xclud/dart_bidi
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
  file: ^7.0.0
